spring.application.name=cinedesk-api-starter
spring.datasource.url=jdbc:h2:mem:cinedesk;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
server.error.include-stacktrace=never
